### ISSUE TITLE
url not working

### ISSUE THREAD

**Issue by NisooJadhav** [SlenderShield/dictionary_app#1]
The URL to your app should be: **https://muralidharabhat.me/dictionary_app/** instead of **https://muralidharabhat.me/Dictionary_App/** in the about section:
![Untitled](https://user-images.githubusercontent.com/68807845/174448460-cfdd18a8-0c76-4865-8f57-818af38c9ad4.png)

**Comment by SlenderShield** [comment]
I have updated the URL in the about section. Thank you.
